apiVersion: tekton.dev/v1
kind: Pipeline
metadata:

  name: noteworthy-backend

spec:

  tasks:

    - name: fetch-source-code
      params:
        - name: CRT_FILENAME
          value: ca-bundle.crt
        - name: HTTP_PROXY
          value: ''
        - name: HTTPS_PROXY
          value: ''
        - name: NO_PROXY
          value: ''
        - name: SUBDIRECTORY
          value: ''
        - name: USER_HOME
          value: /home/git
        - name: DELETE_EXISTING
          value: 'true'
        - name: VERBOSE
          value: 'false'
        - name: SSL_VERIFY
          value: 'true'
        - name: URL
          value: 'https://github.com/mukesh1327/java17-jboss8-tekton-demo.git'
        - name: REVISION
          value: main
        - name: REFSPEC
          value: ''
        - name: SUBMODULES
          value: 'true'
        - name: DEPTH
          value: '1'
        - name: SPARSE_CHECKOUT_DIRECTORIES
          value: ''
      taskRef:
        kind: Task
        name: git-clone-customtask
      workspaces:
        - name: output
          workspace: source-code


    - name: maven-clean-package
      params:
        - name: GOALS
          value:
            - clean
            - package
        - name: MAVEN_MIRROR_URL
          value: ''
        - name: SUBDIRECTORY
          value: .
      runAfter:
        - fetch-source-code
      taskRef:
        kind: Task
        name: maven-customtask
      workspaces:
        - name: source
          workspace: source-code
        - name: maven_settings
          workspace: mvn-settings



    - name: container-image-build
      params:
        - name: IMAGE
          value: 'image-registry.openshift-image-registry.svc:5000/$(context.pipelineRun.namespace)/java-17-jboss:$(tasks.maven-customtask.results.version)'
        - name: DOCKERFILE
          value: ./Dockerfile.jboss8
        - name: BUILD_ARGS
          value: []
        - name: CONTEXT
          value: .
        - name: STORAGE_DRIVER
          value: vfs
        - name: FORMAT
          value: oci
        - name: BUILD_EXTRA_ARGS
          value: ''
        - name: PUSH_EXTRA_ARGS
          value: ''
        - name: SKIP_PUSH
          value: 'false'
        - name: TLS_VERIFY
          value: 'true'
        - name: VERBOSE
          value: 'false'
      runAfter:
        - maven-clean-package
      taskRef:
        kind: Task
        name: buildah-customtask
        resolver: cluster
      workspaces:
        - name: source
          workspace: source-code


  workspaces:
    - name: source-code
    - name: mvn-settings
