kind: Deployment
apiVersion: apps/v1
metadata:
  name: java-17-jboss1
  labels:
    app: java-17-jboss1
    app.kubernetes.io/component: java-17-jboss1
    app.kubernetes.io/instance: java-17-jboss1
    app.kubernetes.io/name: java-17-jboss1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: java-17-jboss1
  template:
    metadata:
      labels:
        app: java-17-jboss1
        deployment: java-17-jboss1
    spec:
      containers:
        - name: java-17-jboss1
          image: 'image-registry.openshift-image-registry.svc:5000/app-deploy-demo/java-17-jboss2:latest'
          ports:
            - containerPort: 8080
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      securityContext: {}
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
